dual_laser_merger_node:
  ros__parameters:
    # Frame and Topic Configuration
    target_frame: "base_footprint"      # The center of the robot
    laser_1_topic: "/f_scan"       
    laser_2_topic: "/b_scan"      
    
    # Scanner Specifications 
    publish_rate: 12.5             # Hz 
    angle_increment: 0.008726      # match the real scan topic from the mir100
    scan_time: 0.08                # 1 / 12.5 = 0.08
    range_min: 0.3                 # 30 cm minimum range
    range_max: 10.0                # 10 meters max range
    min_height: -1.0               # Z-axis crop (ignore ground hits)
    max_height: 1.0                # Z-axis crop (ignore ceiling hits)
    angle_min: -3.14159            # Full 360 degree output (-180 deg)
    angle_max: 3.14159             # Full 360 degree output (+180 deg)
    use_inf: True                  # Use 'inf' for out-of-range beams